### PR TITLE
Lesson linear regression

### PR DESCRIPTION
**Pull request by Ansper11**
Linear regression Python implementation

### CODE REVIEW

**Comment by Ansper11** [comment]
Hi everyone this is our lesson1 python implementation Until OLS algorithm part. I will update the SK-learn part and agent programming part in the following week

**Comment by Nick-McGee** [comment]
Awesome! Would you be able to try and implement this into the main program in the lesson1.json?

**Comment by Ansper11** [comment]
Yes I can try this in the following week

**Comment by eloiseespel** [comment]
Love it, well-developed, a lot of thoughts went into it and you are doing a good job adapting to the age group. I'll try to keep it consistent for lesson 2. Keep going!

**Pull request merged**
