### PR TITLE
Added ideas for lesson 2 

### PR DESCRIPTION
**Pull request by eloiseespel**
I spent most of this week learning about non linear regression and pytorch

### CODE REVIEW

**Comment by Ansper11** [comment]
I think we should pay more attention to how to combine the game and the lesson. For each lesson, we'd better have a reasonable story that students can use some ML algorithms to complete tasks in the game. Therefore, I think you could make a story plan first (the story and the corresponding algorithm) and learn the algorithm in-depth after the plan.

**Comment by Nick-McGee** [comment]
I think the ML approach is better, that way there isn't too much regression and we get a broader intro course. I think Andy and you should work together to use just one ML library, since he wants to use sci-kit learn and you've suggested PyTorch.

**Comment by eloiseespel** [comment]
I see your point Andy I just have never done non linear regression nor have I used pytorch so it is hard for me to come up with a story without understanding the concept. But I'll definitely focus on that next week then

**Comment by eloiseespel** [comment]
Alright I'll just keep sci-kit and make a lesson using that Nick

**Pull request merged**
