### PR TITLE
changes in non-functional requirements

### PR DESCRIPTION
**Pull request by yyht6300a**

### CODE REVIEW

**Comment by Ansper11** [comment]
I think the game will not return a summary after the user finished the lesson

**Comment by Ansper11** [comment]
thanks for updating the user group

**Comment by Nick-McGee** [comment]
I like the idea of adding hints!

**Comment by Nick-McGee** [comment]
The users group are better defined now.

**Comment by eloiseespel** [comment]
This is great, the non functional requirements is a piece of feedback that came back a lot from comments on our presentation

**Comment by eloiseespel** [comment]
I think those are definitely more detailed

**Pull request merged**
